### ISSUE TITLE
Possible issue with CVT module restart

### ISSUE THREAD

**Issue by GCraftsman** [LabVIEW-DCAF/LabVIEW-DCAF.github.io#1]
I could be wrong... 'CVT runtime.lvclass:close.vi' should probably call 'Clear Current Value Table.vi' so that if you reload a configuration without restarting the Main application, you'll get a fresh CVT.  I haven't tested behavior of this... it's just an assumption.

**Comment by GCraftsman** [comment]
Entered this under the the wrong module... I'll move it under CVT.  Feel free to close or delete this issue.

**Comment by Beazurt** [comment]
Duplicate of https://github.com/LabVIEW-DCAF/CVTModule/issues/8
